---
- name: Configure Ubuntu Server
  hosts: "*"
  become: true
  tasks:
    - name: Append custom nano keybindings to nanorc
      copy:
        content: |
          bind ^V paste all
          bind ^Q exit all
          bind ^S savefile main
          bind ^W writeout main
          bind ^O insert main
          set multibuffer
          bind ^H help all
          bind ^H exit help
          bind ^F whereis all
          bind ^G findnext all
          bind ^B wherewas all
          bind ^D findprevious all
          bind ^R replace main
          bind ^Z undo main
          bind ^Y redo main
          unbind ^K main
          unbind ^U all
          unbind ^N main
          unbind ^Y all
          unbind M-J main
          unbind M-T main
          bind ^A mark main
          bind ^P location main
          bind ^T gotoline main
          bind ^T gotodir browser
          bind ^T cutrestoffile execute
          bind ^L linter execute
          bind ^E execute main
        dest: /etc/nanorc
        owner: root
        group: root
        mode: '0644'
