---
- name: Install PSWindowsUpdate module and run Windows Update
  hosts: all
  become: yes
  become_method: runas
  tasks:
    - name: Install NuGet provider if not present
      win_shell: |
        if (-not (Get-PackageProvider -Name NuGet -Force -ErrorAction SilentlyContinue)) {
          Install-PackageProvider -Name NuGet -Force -Scope CurrentUser
        }
      args:
        executable: powershell.exe

    - name: Install PSWindowsUpdate module
      win_shell: |
        Install-Module -Name PSWindowsUpdate -Force -Scope CurrentUser
      args:
        executable: powershell.exe

    - name: Run Windows Update with elevated privileges
      win_shell: |
        Start-Process powershell.exe -ArgumentList "Get-WindowsUpdate -AcceptAll -Install -IgnoreReboot" -Verb RunAs
      args:
        executable: powershell.exe
