---

- name: Reboot windows
  hosts: all
  become: false
  gather_facts: true
  tasks:
    - name: Reboot Windows Machine
      ansible.windows.win_reboot:
        reboot_timeout: 1200
        pre_reboot_delay: 5
        post_reboot_delay: 0
