---

- name: Reboot Windows
  hosts: all
  become: false
  vars_files:
    - /opt/credentials.yml
  gather_facts: true
  ignore_unreachable: true
  tasks:
    - name: Reboot Windows Machine
      ansible.windows.win_reboot:
        reboot_timeout: 3600
        pre_reboot_delay: 5
        post_reboot_delay: 0
