---

- name: Reboot windows
  hosts: all
  become: false
  gather_facts: false
  tasks:
    - name: Reboot Windows Machine
      ansible.windows.win_reboot:
#        pre_reboot_delay: 5
#        post_reboot_delay: 120
