---

- name: win_update module
  hosts: all
  become: false
  gather_facts: true
  ignore_unreachable: true
  tasks:
    - name: Install all updates and don't reboot
      ansible.windows.win_updates:
        ignore_errors: true
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
          - Updates
        reboot: false
        log_path: c:\temp\update.log
