---
- name: Execute PowerShell Script
  hosts: all
  become: false
  vars_files:
    - /opt/credentials.yml
  gather_facts: true
  ignore_unreachable: true
  tasks:
  #  - name: Copy PowerShell Script
  #    win_copy:
  #      src: path/to/your/script.ps1
  #      dest: C:\path\on\remote\script.ps1
  #
    - name: Execute PowerShell Script
      win_shell: |
        $scriptPath = "C:\scripts\updatefiles.ps1"
        powershell -ExecutionPolicy Bypass -File $scriptPath
