---

- name: win_update module
  hosts: all
  become: false
  gather_facts: true
  tasks:
    - name: Install all updates and reboot
      ansible.windows.win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
          - Updates
-       state: installed
        log_path: c:\temp\update.log
        async: 0  # Run this task asynchronously
        poll: 0   # Do not wait for the task to complete
        reboot: true