---

- name: win_update module
  hosts: all
  become: false
  gather_facts: true
  ignore_unreachable: true
  tasks:
    - name: Ensure log directory exists
      ansible.windows.win_file:
        path: c:\temp
        state: directory

    - name: Remove existing log file
      ansible.windows.win_file:
        path: c:\temp\update.log
        state: absent
      ignore_errors: true

    - name: Install all updates and no reboot
      ansible.windows.win_updates:
        reboot: false
        log_path: c:\temp\update.log
        category_names: '*'
