---

- name: win_update module
  hosts: all
  become: false
  gather_facts: true
  ignore_unreachable: true
  tasks:
    - name: Install all updates and don't reboot
      ansible.windows.win_updates:
        reboot: false
        log_path: c:\temp\update.log
        exclude_drivers: yes
        category_names:
          - "Definition Updates"
          - "Microsoft Defender Antivirus"
