---
- name: Install all Windows updates
  hosts: windows_host
  gather_facts: no
  tasks:
    - name: Check for available updates
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
          - Updates
        state: 'installed'
      register: update_result

    - name: Install updates if available
      win_updates:
        category_names:
          - SecurityUpdates
          - CriticalUpdates
          - UpdateRollups
          - Updates
        state: 'installed'
        reboot: yes
      when: update_result.updates | length > 0